### PR TITLE
Add support for FLAMEGPU_ROOT CMake var

### LINKED ISSUE #7: Allow using local FLAMEGPU2 via Cmake
It would be useful to support non-FetchContent based inclusion of FLAMEGPU/FLAMEGPU2.

Ideally, this would use a `find_package(flamegpu2)` checking default locations / allow users to specify the location to search by a cache variable, but withotu install rules / config files this is not overly feasible yet. 

Instead, the approach that would match the visualisation root style approach would be to allow users to specify `FLAMEGPU_ROOT` themselves, in which case the CMake FetchContent version is not checked, and the appropraite `add_subdirectory` command is issued. 

This would improve the use of standalone projects when developing core FLAMEGPU2 features.

This would need propagating to existing standalone repos based on this template.

### PR DESCRIPTION
**Pull request by Robadob**
This is the version I've tested in Primage repo.

I've tested that it works when enabled, not tested that somehow I've broken when it's disabled.

Closes #7

### CODE REVIEW

**Comment by Robadob** [comment]
SQUASH ME ON MERGE

**Review by ptheywood — APPROVED** [review]
Works well, can be reset for a directory by `cmake .. -DFLAMEGPU_VERSION=` which will then fetch the version as specified by `FLAMEGPU_VERSION`.

Long term we should switch this to some combo of `find_package(flamegpu)` etc, but that will require many extra steps (should be covered in an existing core repo issue). 

Needs adding to the `README`, but I'll do that now prior to merging.

**Review by ptheywood — CHANGES_REQUESTED** [review]
Scratch that, doesn't work well if a bad path is passed, but it is still managing to find my local version somehow. 

```
cmake .. -DFLAMEGPU_ROOT=/invalid/path/
-- Found FLAMEGPU_ROOT: /home/ptheywood/code/flamegpu/FLAMEGPU2 (/invalid/path/)
```

**Comment by Robadob** [comment]
I presume it's failing silently, then falling back to old behaviour. The VISUALISATION_ROOT behaviour in fgpu repo probably the same.

**Comment by ptheywood** [comment]
> I presume it's failing silently, then falling back to old behaviour. The VISUALISATION_ROOT behaviour in fgpu repo probably the same.

`find_path(FLAMEGPU_ROOT_ABS ...` is finding my local copy even though it is not within the hinted or path subdirectories. Might need to pass some other options to find_path so it doesn't find it when it shouldn't. I'll try and fix it.

**Comment by ptheywood** [comment]
Ah find_path caches the path when it finds one unless `NO_CACHE` is passed, so it was remembering the location I told it about earlier. Will push a fix when I've tidied it up. 

Also, attempting to overide `FLAMEGPU_VERSION` from the command line (as suggested in the readme) doesn't work if it is set in the CMAkeLists.txt (as a non cache variable). 

Setting it as a cache variable however, means that if the CMakeLists.txt is changed, it will not change the value used (I.e. recent ensemble benchmarking issue, which does set it as a cache variable not a local). I am not certain what the best setup for this is.

**Review by ptheywood — APPROVED** [review]
Approving my own changes as @Robadob won't be able to review his own PR...

**Pull request merged**
